</div>
    <div acao="carregar_filtro" class="filter-results-options filter-form">
    <div chave="filtros" class="field-block">
    <?php
        foreach($filters as $filter) {
            $filter->render();
        }
    ?>

    <div class="filter-results-item visivel">
        <p class="filter-results-title"><strong>Lido</strong></p>

        <span class="box-list-spacer"></span>

        <fieldset class="field checkboxGruop">
            <label class="placeholder">
                <input type="checkbox" autocomplete="off" radio="visivel" class="placeholder-check" value="0" name="lido_false" />
                <p class="field-text">Não</p>
            </label>

            <label class="placeholder">
                <input type="checkbox" autocomplete="off" radio="visivel" class="placeholder-check" value="1" name="lido_true" />
                <p class="field-text">Sim</p>
            </label>
        </fieldset>
    </div>
        <button title="Filtrar" class="botao filtro"><span><var></var><em>Filtrar</em></span><var class="borda"></var></button>
</div>
