<?php if(!isset($disableBreadcrumbs)) : ?>

  <?php
    $breadcrumbs = \AckCore\View\Helper\BreadCrumbs::Factory(array("title"=>$title,"disablePluralizer"=>$disableTitlePluralizer));
  ?>

  <div id="breadcrumbs">
    <?php if(!$disableBackButtons && !$disableBack) : ?>
    <a title="Voltar" class="btnSeta voltarTopo" href="/ack/<?= $controllerName?>">Voltar</a>
    <?php endif; ?>

    <ul>
      <?php
         while($breadcrumbs->getCurrent()) :
            $current = $breadcrumbs->getCurrent();
            if($breadcrumbs->getNext()) :

      ?>
         <li><a title="<?php echo $current["string"] ?>" href="<?php echo $current["url"] ?>">
          <em><?php echo $current["string"] ?></em></a></li>

          <?php else : ?>

           <li><span  >
          <em><?php echo $current["string"] ?></em></span></li>
          <?php endif; ?>

      <?php
          $breadcrumbs->increment();
        endwhile;
       ?>
    </ul>
  </div><!-- END breadcrumbs -->

<?php endif; ?>
