<?php
    $system = \AckCore\Model\Systems::getMainSystem();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link rel="Shortcut Icon" type="image/ico" href="/ack-core/images/favicon.gif" />
    <title><?php echo $system->getnomesite()->getVal() ?> -<?php echo \AckCore\Facade::getAckVersion(); ?> <?php echo $title; ?></title>

    <link type="text/css" rel="stylesheet" href="/ack-core/css/ack.style.css" />
    <!--[if IE 7]> <link type="text/css" rel="stylesheet" href="/ack-core/css/ack.style_IE7.css" /> <![endif]-->
    <!--[if IE 8]> <link type="text/css" rel="stylesheet" href="/ack-core/css/ack.style_IE8.css" /> <![endif]-->
    <!--[if IE 9]> <link type="text/css" rel="stylesheet" href="/ack-core/css/ack.style_IE9.css" /> <![endif]-->

    <script>var siteURL="<?php echo \AckCore\Facade::getServerName(); ?>";</script>

    <script type="text/javascript" src="/plugins/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/plugins/jquery-ui-1.9.2.custom.min.js"></script>
    <script type="text/javascript" src="/plugins/json2.js"></script>


    <?php if (isset($plugins)) : ?>
    <!-- |||||||||| plugin para drag'n drop ||||||||||
    <script type="text/javascript" src="/plugins/ack/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="/plugins/ack/jquery.tablednd.0.7.min.js"></script> -->

    <!-- |||||||||| plugin para upload de arquivos |||||||||| -->
    <script type="text/javascript" src="/plugins/uploads/jquery.uploadify.v2.1.4.js"></script>
    <script type="text/javascript" src="/plugins/uploads/swfobject.js"></script>
    <script type="text/javascript" src="/ack-core/js/script.ack_uploadFiles.js"></script>

    <!-- |||||||||| plugin para crop de imagens |||||||||| -->
    <link type="text/css" rel="stylesheet" media="all" href="/plugins/ack/jCrop/jquery.Jcrop.min.css" />
    <script type="text/javascript" src="/plugins/ack/jCrop/jquery.Jcrop.min.js"></script>
    <script type="text/javascript" src="/plugins/ack/jCrop/jquery.color.js"></script>
    <?php endif; ?>

    <?php if (isset($dragDrop)) : ?>
    <script type="text/javascript" src="/plugins/ack/jquery-ui.min.js"></script>
    <!-- |||||||||| plugin para drag'n drop |||||||||| -->
    <script type="text/javascript" src="/plugins/ack/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="/plugins/ack/jquery.tablednd.0.7.min.js"></script>
    <?php endif; ?>

    <?php if (isset($autoComplete) && !isset($dragDrop)) : ?>
    <script type="text/javascript" src="/plugins/ack/jquery-ui.min.js"></script>
    <?php endif; ?>


    <!-- |||||||||| plugin para editor de texto |||||||||| -->
    <script type="text/javascript" src="/plugins/ack/tinymce/tinymce.min.js"></script>

    <!---->
    <script type="text/javascript" src="/ack-core/js/script.funcoes.ack.js"></script>
    <script type="text/javascript" src="/ack-core/js/script.ack.js"></script>

    <script type="text/javascript" src="/ack-core/js/script.ack-v2.0.js"></script>
    <script type="text/javascript" src="/ack-core/js/script.devil.js"></script>
</head>
