<div class="row">
    <div class="col-xs-12">
        <div class="jumbotron">
            <h2>Bem-vindo(a)!</h2>
            <p>Utilize abaixo seu email e senha para ingressar no sistema.</p>
        <?php
            $formLogin->prepare();
            $formLogin->setAttribute('action', $this->url('login-reciver'));
            echo $this->formTwb($formLogin);
        ?>
        </div>
    </div>
</div>
