<?php
  // \AckCore\Utils::dg($filters);
?>

</div>
    <div acao="carregar_filtro" class="filter-results-options filter-form">
    <div chave="filtros" class="field-block">
    <?php
        foreach($filters as $filter) {
            $filter->render();
        }
    ?>
    <div class="filter-results-item statusImagem">
    <p class="filter-results-title"><strong>Filtro de Status</strong></p>

    <span class="box-list-spacer"></span>

    <fieldset class="field">
        <p class="field-text">Status:</p>
        <label class="placeholder">
            <select name="categoria_id" class="placeholder-select">
                <option value="">Todos</option>
                <?php foreach ($categorys as $category) :

                ?>
                <option value="<?php echo $category->getId()->getBruteVal(); ?>"><?php echo $category->getTitulo()->getVal(); ?></option>
             <?php endforeach; ?>

            </select>
        </label>
    </fieldset>
</div>
    <button title="Filtrar" class="botao filtro"><span><var></var><em>Filtrar</em></span><var class="borda"></var></button>
</div>
