<nav class="navbar navbar-default hidden-print" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Alternar navega&ccedil;&atilde;o</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<!-- <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-briefcase"></span>&nbsp;Est&aacute;gios</a> -->
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<?php
			$partial = array('/site-jean/layout/partials/navigation/menu.phtml', 'default');
			echo $this->navigation('navigation')->menu()->setPartial($partial)->setMinDepth(0)->setMaxDepth()->setUlClass('nav navbar-nav')->render();
		?>
	</div><!-- /.navbar-collapse -->
</nav>
