<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckCEO\Module'                        => __DIR__ . '/Module.php',
    'AckCEO\Model\NewRow'                  => __DIR__ . '/src/AckCEO/Model/NewRow.php',
    'AckCEO\Model\News'                    => __DIR__ . '/src/AckCEO/Model/News.php',
);
