<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    // 'AckContent\Module'                             => __DIR__ . '/Module.php',
    // 'AckContent\Model\Institutional'                => __DIR__ . '/src/AckContent/Model/Institutional.php',
    // 'AckContent\Model\Text'                         => __DIR__ . '/src/AckContent/Model/Text.php',
    // 'AckContent\Model\ContentController'            => __DIR__ . '/src/AckContent/Model/ContentController.php',
    // 'AckContent\Model\Highlights'                   => __DIR__ . '/src/AckContent/Model/Highlights.php',
    // 'AckContent\Model\Texts'                        => __DIR__ . '/src/AckContent/Model/Texts.php',
    // 'AckContent\Model\Contents'                     => __DIR__ . '/src/AckContent/Model/Contents.php',
    // 'AckContent\Model\ContentControllers'           => __DIR__ . '/src/AckContent/Model/ContentControllers.php',
    // 'AckContent\Model\Institutionals'               => __DIR__ . '/src/AckContent/Model/Institutionals.php',
    // 'AckContent\Model\Highlight'                    => __DIR__ . '/src/AckContent/Model/Highlight.php',
    // 'AckContent\Model\Content'                      => __DIR__ . '/src/AckContent/Model/Content.php',
    // 'AckContent\Controller\ConteudosController'     => __DIR__ . '/src/AckContent/Controller/ConteudosController.php',
    // // 'AckContent\Controller\DestaquesController'     => __DIR__ . '/src/AckContent/Controller/DestaquesController.php',
    // 'AckContent\Controller\TextosController'        => __DIR__ . '/src/AckContent/Controller/TextosController.php',
    // 'AckContent\Controller\InstitucionalController' => __DIR__ . '/src/AckContent/Controller/InstitucionalController.php',
);
