destination: _build

# Blog settings
permalink: /blog/:title.html

# My variables
name: Jean Carlo Machado
description: My personal blog
google_verification: null
keywords: Jean, Developer, Sowftware

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels:     1..6

