destination: dist

# Blog settings
permalink: /blog/:title.html

# My variables
name: Jean Carlo Machado
description: My personal blog
google_verification: null
keywords: Jean, Developer, Sowftware
url: http://jeancarlomachado.com.br/

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..6

