apache:
    environment:
        BLOG_HOST:
    image: eminetto/apache
    ports:
        - "80:80"
    volumes:
        - .:/var/www/html/blog
        - ./apache/dev.conf:/etc/apache2/sites-enabled/001-clipp.conf
    links:
        - mysql
mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=blog
        - MYSQL_USER=blog
        - MYSQL_PASSWORD=blog
    command : /entrypoint.sh --sql-mode='STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

