<?php
    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
?>
<div>
    <h1 style="display:inline"><?php echo $row->getTitulo()->getVal(); ?></h1><small> (<?php echo $row->getData()->getVal(); ?>)</small>
    <div>

        <?php

        $parsedown = new \Parsedown();
        echo $parsedown->text($row->getConteudo()->getVal());

        ?>
    </div>
<div>
    <button type="button" class="btn btn-info" onclick="window.history.back();">Voltar</button>
</div>

</div>

<hr />

<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'jeancarlomachado'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
