<?php

    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
    $filter = new Zend\Filter\StripTags(array('allowTags' => 'br div hr b'));
?>
<h5>Latest Posts</h5>

<section>
<?php
foreach($this->posts as $post) :
?>
<article>
    <h3 style="display:inline"><a href="<?php echo $this->url('view-post', array ('id' => $post->getId()->getVal())) ?>"><?php echo $post->getTitulo()->getVal(); ?></a></h3><small> (<?php echo $post->getData()->getVal(); ?>)</small>
    <div >
        <?php echo $filter->filter($post->getConteudo()->showNChars(500)->getVal()); ?>
    </div>

</article>
<hr>
<?php
endforeach;
?>
</section>


<?php
if ($currentPage >= 1) :
?>
<a class="btn btn-info" href="/?page=<?php echo $currentPage -1 ?>">Newer</a>
<?php
endif;
?>

<?php
 if ($currentPage <= $totalPages) :
?>
<a class="btn btn-info" id="navigationOlder" href="/?page=<?php echo $currentPage+1 ?>">Older</a>
<?php
 endif;
?>

