

<div class="parentFull" id="dashboard">

    <!-- • • • • -->
    <div class="modulo Wfull" id="dadosSite">

        <h2>Informações gerais</h2>

        <!-- • • • • -->
        <ul>
             <li>Versão do Ack: <var><?php echo \AckCore\Facade::getAckVersion() ?></var></li>
        	<li>Versão do PHP:           <var><?php echo phpversion() ?></var></li>
        	<li>Document Root:           <var><?php echo $_SERVER["DOCUMENT_ROOT"] ?></var></li>
        	<li>Nome do banco de dados principal: <var><?php echo \AckDb\ZF1\Utils::getDatabaseName() ?></var></li>
            <li>Módulos ZF2 Habilitados: <var><?php echo substr(\AckCore\Utils\Arr::implodeRecursively(\AckCore\Facade::getModulesEnabled(),null,", ",true),0,-2) ?></var></li>
            <li>Documentação Doxygen:<var><?php echo $_SERVER['DOCUMENT_ROOT'] ?>/../docs/doxygen/html/index.html</var></li>
       </ul>

       <!-- • • • • -->
       <p>Mais Informações: <a href="/ack/devel/dashboard/phpinfo" target="_blank" title="">PHP-Info</a></p>
       <p>Visualizar o site: <a href="<?php echo \AckCore\Facade::getEnderecoSite(); ?>" target="_blank" title=""><?php echo \AckCore\Facade::getEnderecoSite(); ?></a></p>
       <p>Esquema do banco: <a href="<?php echo $this->url('AckDevel/default', array('controller' => 'dashboard', 'action' => 'database')); ?>" target="_blank" title="">Schema</a></p>
