<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>My goals</title>
    <meta charset="utf-8">
    <meta name="robots" content="noindex">

</head>
<body>
    <div>
        <h3><?php echo $row->getTitulo()->getVal(); ?></h3>

        <div>
            <?php
                $parsedown = new \Parsedown();
                echo $parsedown->text($row->getConteudo()->getVal());
            ?>
        </div>
    </div>

    <hr />

    </body>
</html>
