<?php
    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
?>
<h5>Últimas postagens</h5>

<div>
<?php
foreach($this->posts as $post) :
?>
<div>
    <h3><?php echo $post->getTitulo()->getVal(); ?></h3>

    <div>
        <?php echo $post->getConteudo()->showNChars(500)->getVal() ?>
    </div>

    <?php
    $serviceLocator->get('HtmlElementsManager')->getInstanceOf('Button')
        ->setName('view-details')
        ->setValue('Leia mais')
        ->setTitle('Leia mais')
        ->setPermission('+rw')
        ->appendClass('btn btn-success')
        ->setUrl($this->url('view-post', array ('id' => $post->getId()->getVal(), 'title' => $post->getTitulo()->toUrl()->getVal())))
        ->render();

    ?>
</div>

<hr />

<?php
endforeach;
?>

<div>
