<?php
    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
    $filter = new Zend\Filter\StripTags(array('allowTags' => '<br><div>'));
?>
<h5>Últimas postagens</h5>

<div>
<?php
foreach($this->posts as $post) :
?>
<hr />
<div>
    <h3 style="display:inline"><?php echo $post->getTitulo()->getVal(); ?></h3><small> (<?php echo $post->getData()->getVal(); ?>)</small>
    <br />
    <br />
    <div >
        <?php echo $filter->filter($post->getConteudo()->showNChars(500)->getVal()); ?>
    </div>

    <?php
    $serviceLocator->get('HtmlElementsManager')->getInstanceOf('Button')
        ->setName('view-details')
        ->setValue('Leia mais')
        ->setTitle('Leia mais')
        ->setPermission('+rw')
        ->appendClass('btn btn-success')
        ->setUrl($this->url('view-post', array ('id' => $post->getId()->getVal(), 'title' => $post->getTitulo()->toUrl()->getVal())))
        ->render();

    ?>
</div>

<?php
endforeach;
?>

<div>
