<?php
    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
    $filter = new Zend\Filter\StripTags(array('allowTags' => 'br div hr b'));
?>
<h5>Últimas postagens</h5>

<div>
<?php
foreach($this->posts as $post) :
?>
<hr />
<div>
    <h3 style="display:inline"><a href="<?php echo $this->url('view-post', array ('id' => $post->getId()->getVal())) ?>"><?php echo $post->getTitulo()->getVal(); ?></a></h3><small> (<?php echo $post->getData()->getVal(); ?>)</small>
    <div >
        <?php echo $filter->filter($post->getConteudo()->showNChars(500)->getVal()); ?>
    </div>

</div>

<?php
endforeach;
?>


<div id="historyNavigationButtons">
<?php
if ($currentPage >= 1) :
?>
<a  class="btn btn-default" href="/?page=<?php echo $currentPage -1 ?>">Novos</a>
<?php
endif;
?>

<?php
 if ($currentPage =< $totalPages) :
?>
<a class="btn btn-default" id="navigationOlder" href="/?page=<?php echo $currentPage+1 ?>">Antigos</a>
<?php
 endif;
?>

</div>

<div>
