<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SiteJean\Module'                              => __DIR__ . '/Module.php',
    'SiteJean\Model\Institutional'                 => __DIR__ . '/src/SiteJean/Model/Institutional.php',
    'SiteJean\Model\Institutionals'                => __DIR__ . '/src/SiteJean/Model/Institutionals.php',
    'SiteJean\View\Helper\BreadCrumbs'             => __DIR__ . '/src/SiteJean/View/Helper/BreadCrumbs.php',
    'SiteJean\Controller\ServicosController'       => __DIR__ . '/src/SiteJean/Controller/ServicosController.php',
    'SiteJean\Controller\Helper\SearchProducts'    => __DIR__ . '/src/SiteJean/Controller/Helper/SearchProducts.php',
    'SiteJean\Controller\Helper\BudgetPersistence' => __DIR__ . '/src/SiteJean/Controller/Helper/BudgetPersistence.php',
    'SiteJean\Controller\ProdutosController'       => __DIR__ . '/src/SiteJean/Controller/ProdutosController.php',
    'SiteJean\Controller\PedidosController'        => __DIR__ . '/src/SiteJean/Controller/PedidosController.php',
    'SiteJean\Controller\InstitucionalController'  => __DIR__ . '/src/SiteJean/Controller/InstitucionalController.php',
    'SiteJean\Controller\UsuariosController'       => __DIR__ . '/src/SiteJean/Controller/UsuariosController.php',
    'SiteJean\Controller\ContatosController'       => __DIR__ . '/src/SiteJean/Controller/ContatosController.php',
    'SiteJean\Controller\OrcamentosController'     => __DIR__ . '/src/SiteJean/Controller/OrcamentosController.php',
    'SiteJean\Controller\IndexController'          => __DIR__ . '/src/SiteJean/Controller/IndexController.php',
);
