<?php
	$layoutName = \AckCore\Facade::getLayoutName();
	//pega o viewmodel do controlador
	$children = $this->viewModel()->getCurrent()->getChildren();
	$child = $children[0];
	$variables = $child->getVariables();
	if(is_object($variables))
		extract($variables->getArrayCopy());
?>
<?php require_once("$layoutName/header.phtml"); ?>
<?php
    $containerName = "$layoutName/containerElement";
    $containerName.= (\AckCore\Utils\File::getFileStr($child->getTemplate()) == \AckMvc\Controller\TableRowAutomatorAbstract::PLURAL_VIEW_NAME)  ? "s" : "";
    $containerName.= ".phtml";
    require_once $containerName;
?>
<?php require_once("$layoutName/footer.phtml"); ?>
