<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckCMS\Module'                        => __DIR__ . '/Module.php',
    'AckCMS\Model\NewRow'                  => __DIR__ . '/src/AckCMS/Model/NewRow.php',
    'AckCMS\Model\News'                    => __DIR__ . '/src/AckCMS/Model/News.php',
);
