<div class="modulo <?= $controllerName ?>">
    <?php \AckCore\HtmlElements\Explain::getInstance()->setName("moduleDescription")->render();?>

    <div class="slide colunas">
        <div class="collumA form">

            <?php
                     \AckCore\HtmlElements\Input::Factory($row->vars["nome"])->render();
            ?>

        </div><!-- END collumA -->
        <!-- • • • • -->
        <div class="collumB">
                       <?php echo $this->visible($row,$disableVisible) ?>
            <?php
            \AckCore\HtmlElements\LanguageSelector::getInstance()->render() ?>

              <?php
                $automator = new \AckCore\HtmlElements\Automator;
                unset($config["blacklist"]);
                $config["whitelist"] = (is_array($colB["whitelist"])) ? $colB["whitelist"] : array();
                $automator->getProperColumns($row,$config);
            ?>

        </div>

        <span class="clearBoth"></span>
    </div><!-- END slide -->
</div><!-- END modulo -->

<?php if($row->getId()->getBruteVal()) : ?>
<div class="modulo childs">
  <?php \AckCore\HtmlElements\Explain::getInstance()->setName("categoriasFilhas")->render();?>
 <?php
         $checksAction = array();
         foreach($childs as $child) {
            $checksAction[] = \AckCore\HtmlElements\Check::getInstance(true)
                                                ->setChecked($child->isChildOf($row))
                                                ->setTitle($child->getNome()->getBruteVal())
                                                ->setValue($child->getId()->getBruteVal())
                                                ->setPermission("+rw")
                                                ->setName("childs");
         }

          $blockActions = \AckCore\HtmlElements\CheckBlock::getInstance()
          ->setChecks($checksAction)
          ->setTitle("Categorias filhas")
          ->setName("childs")
          ->setPermission("+rw")
          ->render();
      ?>
</div>
<?php endif; ?>
