<?php
    $this->config;
    $filters = $this->buildFilters($config);

    if(!empty($filters)) :
?>
    <div class="row hidden-print">
        <div class="col-xs-12">
            <div class="panel panel-default" id="filtros">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <a data-toggle="collapse" data-parent="#filtros" href="#collapseFiltros">Filtros</a>
                        <span id="linkFiltros" class="glyphicon glyphicon-collapse-down"></span>
                    </h3>
                </div>
                <div id="collapseFiltros" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="row">
                            <form class="filtersContainer">
                            <?php
                                foreach ($filters as $filter) {
                                    $filter->render();
                                }
                            ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
    endif;
?>
<div class="row hidden-print">
    <div class="col-xs-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">A&ccedil;&otilde;es</h3>
            </div>
            <div class="panel-body">
                <div class="btn-group">
                <?php
                    if(!empty($filters)) {
                        //botao filtrar
                        $this->htmlManager->getInstanceOf("Link")
                            ->setId('filterButoon')
                            ->appendClass('btn-default')
                            ->setName("filtersDispatcher")
                            ->setValue("Filtrar")
                            ->setTitle("Filtrar")
                            ->setPermission("+rw")
                            ->setUrl('javascript:void(0);')
                            ->render();
                    }

                    //botão adicionar
                    $this->htmlManager->getInstanceOf("Link")
                        ->appendClass('btn-default')
                        ->setName("add")
                        ->setValue("Criar")
                        ->setTitle("Criar")
                        ->setPermission("+rw")
                        ->setUrl($config['urlAdd'])
                        ->render();

                    $config['urlRm'] = (isset($config['urlRm'])) ? $config['urlRm'] : '';

                    //botão excluir
                    $this->htmlManager->getInstanceOf("Link")
                        ->appendClass('btn-default')
                        ->setId('removeRows')
                        ->setName("removeRows")
                        ->setValue("Excluir")
                        ->setTitle("Excluir")
                        ->setPermission("+rw")
                        ->setUrl($config['urlRm'])
                        ->render();
                ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead class="tableHeaderContainer">
                    <tr>
                        <th sytle="width:10px;"><input type="checkbox" name="rowSelectorGlobal" class="globalCheck" ></th>
                        <?php
                            //imprime o cabeçalho da tabela
                            $automator = $this->htmlManager->getInstanceOf("ListInterpreter")->renderHeader($config);
                        ?>
                        <th name="options">Opções</th>
                    </tr>
                </thead>
                <tbody class="elementsContainer"></tbody>
            </table>
        </div>
    </div>
</div>
<div class="row hidden-print">
    <div class="col-xs-12">
        <button name="requestItens" class="loadMoreItens btn btn-default center-block">Carregar mais</button>
        <input type="hidden" class="pageInfo" data-container='{"rowId":"<?php echo $config['row']->getId()->getBruteVal(); ?>","urlGateway":"<?php echo $config['urlGateway'] ?>","actionName":"<?php echo $this->layout()->actionName; ?>"}'/>
    </div>
</div>
