#!/bin/bash

baseUrl=$BLOG_URL
verbose=0

function getHelp {
    printf "
    saves a post on my blog
    $0 <postId> <full-path-to-file-with-content>
"
echo "\n"
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}


[ $(isEmpty $@) != 0 ] || [ $(isEmpty $1) != 0 ] || [ $(isEmpty $2) != 0 ] && {
    printf "$(getHelp)"
    exit 0
}


[[ $3 = '-v' ]] && {
	verbose=1
	echo "Verbose Found"
}

fileWthContent=$2

if [ ! -e $fileWthContent ]; then
    printf "$(getHelp)"
    exit 0
fi

postId=$1

newContent=`cat $fileWthContent`

data="$newContent"
# data=$(echo $data | url-encode)

request="curl -X PUT  -d \"$data\" $baseUrl/root/post/$postId"
echo $request

[[ $verbose = 1 ]] && {
	echo "$request"
}

curl -X PUT -H "Only-Content: encodedBlogContent" -d "$data" $baseUrl/root/post/$postId
