#!/bin/bash

verbose=0
baseUrl="$BLOG_URL/posts/routerAjax"
postId=0

function getHelp {
    printf "
View the posts on my blog

\n "
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}

args=("$@")
for i in "$@"
do
    if [[ "$i" = "--help" ]] || [[ "$i" = "-h" ]]; then
       printf "$(getHelp)"
       exit 0
    elif [[ "$i" = "-v" ]] || [[ "$i" = "--verbose" ]]; then
        verbose=1
        echo "Verbose found"
    elif [[ "$i" =~  ^- ]]; then
        echo "Invalid parameter: $i"
        exit 1
    fi
    counter=$[$counter + 1]
done


jsonData=`curl -X POST -H "Accept-Language: pt_BR" -H "Content-Type:application/x-www-form-urlencoded" -H "Cache-Control: no-cache"  -d "ajaxACK=%7B%22action%22%3A%22loadItens%22%2C%22itensCount%22%3A0%2C+\"itensPerPage\"%3A+1000%7D" $baseUrl`

[ $verbose = 1 ] && {
    echo "Request result $jsonData"



    echo "Listing all posts from $BLOG_URL"
}

counter=0
while [[ $( echo `node -pe "JSON.parse(process.argv[1]).grupo[$counter].id" "$jsonData" 2> /dev/null ` | grep -v "undefined")  ]] ; do
    printf `node -pe "JSON.parse(process.argv[1]).grupo[$counter].id" "$jsonData"`
    printf ' - '
    echo `node -pe "JSON.parse(process.argv[1]).grupo[$counter].titulo" "$jsonData"`

    counter=$[$counter + 1]
done
