#!/bin/bash

baseUrl=$BLOG_URL

function getHelp {
    printf "
    saves a post on my blog
    $0 <postId> <full-path-to-file-with-content>
"
echo "\n"
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}

[ $(isEmpty $@) != 0 ] || [ $(isEmpty $1) != 0 ] || [ $(isEmpty $1) != 0 ] && {
    printf "$(getHelp)"
    exit 0
}

fileWthContent=$2

if [ ! -e $fileWthContent ]; then
    printf "$(getHelp)"
    exit 0
fi

postId=$1

newContent=`cat $fileWthContent`
newContent="${newContent//\\/\\\\}"
newContent="${newContent//\'/\'}"
newContent="${newContent//\"/\\\"}"
newContent="${newContent//\//\\/}"
newContent="${newContent//
/\\n}"

jsonData='{"data":{"default":{"id":"'$postId'", "conteudo":"'$newContent'"}},"parameters":"","id":"'$postId'","action":"save"}'

jsonEncodedData=`echo "$jsonData" | json-urlencode`
jsonEncodedData='ajaxACK='"$jsonEncodedData"
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Connection: keep-alive" -H "Cache-Control: no-cache" -d $jsonEncodedData $baseUrl/posts/routerAjax
