#!/bin/bash

verbose=0
baseUrl="$BLOG_URL/root/posts"
postId=0

function getHelp {
    printf "View the posts on my blog"
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}

args=("$@")
for i in "$@"
do
    if [[ "$i" = "--help" ]] || [[ "$i" = "-h" ]]; then
       printf "$(getHelp)"
       exit 0
    elif [[ "$i" = "-v" ]] || [[ "$i" = "--verbose" ]]; then
        verbose=1
        echo "Verbose found"
    elif [[ "$i" =~  ^- ]]; then
        echo "Invalid parameter: $i"
        exit 1
    fi
    counter=$[$counter + 1]
done


curlCommand="curl $baseUrl?resume=1"
jsonData=`$curlCommand`

[ $verbose = 1 ] && {
    echo $curlCommand
    echo "Request result $jsonData"
    echo "Listing all posts from $BLOG_URL"
}

counter=0
while [[ $( echo `node -pe "JSON.parse(process.argv[1])[$counter].id" "$jsonData" 2> /dev/null ` | grep -v "undefined")  ]] ; do
    printf `node -pe "JSON.parse(process.argv[1])[$counter].id" "$jsonData"`

    printf ' - '
    printf `node -pe "JSON.parse(process.argv[1])[$counter].publicado" "$jsonData"`
    printf ' - '
    echo `node -pe "JSON.parse(process.argv[1])[$counter].titulo" "$jsonData"`

    counter=$[$counter + 1]
done
