#!/bin/bash

verbose=0
baseUrl=$BLOG_URL
postId=0

function getHelp {
    printf "
Edit an post on my blog
Usage:\n
$0 --post-id postId

Optional paramters:
--base-url http://base-url

Examples:
None
\n "
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}

[ $(isEmpty $@) != 0 ] && {
    printf "$(getHelp)"
    exit 0
}

if [ $(isEmpty $1) == 0 ] && [ $(isEmpty $2) != 0 ]; then
    postId=$1
else
    args=("$@")
    for i in "$@"
    do
        if [[ "$i" = "--help" ]] || [[ "$i" = "-h" ]]; then
        printf "$(getHelp)"
        exit 0
        elif [[ "$i" = "-v" ]] || [[ "$i" = "--verbose" ]]; then
            verbose=1
            echo "Verbose found"
        elif [[ "$i" = "-i" ]] || [[ "$i" = "--post-id" ]]; then
            postId=${args[$counter + 1]}
        elif [[ "$i" = "-m" ]] || [[ "$i" = "--metadata" ]]; then
            metadata=${args[$counter + 1]}
        elif [[ "$i" = "--base-url" ]]; then
            baseUrl=${args[$counter + 1]}
        elif [[ "$i" = "--destination" ]]; then
            destination=${args[$counter + 1]}
        elif [[ "$i" =~  ^- ]]; then
            echo "Invalid parameter: $i"
            exit 1
        fi
        counter=$[$counter + 1]
    done
fi

[ -z $destination ]  && {
    destination="/tmp/post-$postId-$$.md"
}

curl $baseUrl/root/post/$postId

[[ $verbose = 1 ]] && {
    echo "Saving location: $destination"
}

sonData=`$request`

[[ $verbose = 1 ]] && {
    echo "Result: $jsonData"
}

json-is-valid "$jsonData"

if [ $? -ne 0 ]; then
    echo "Invalid JSON return"
    exit 1
fi

if [ -z $metadata ]; then 

    content=`node -pe 'JSON.parse(process.argv[1]).conteudo' "$jsonData"`

else

title=`node -pe 'JSON.parse(process.argv[1]).titulo' "$jsonData"`
date=`node -pe 'JSON.parse(process.argv[1]).data' "$jsonData"`
published=`node -pe 'JSON.parse(process.argv[1]).publicado' "$jsonData"`
description=`node -pe 'JSON.parse(process.argv[1]).description' "$jsonData"`
keywords=`node -pe 'JSON.parse(process.argv[1]).keywords' "$jsonData"`

content="Title=$title
Date=$date
Published=$published
Description=$description
Keywords=$keywords

"

fi

echo "$content" > $destination

