#!/bin/bash

baseUrl=$BLOG_URL

function getHelp {
    printf "
    saves a new post on my blog
    $0
"
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}

read -p "Type the title: " $title
read -p "Type the description: " $description
read -p "Type the keyworkds: " $keywords


data="conteudo=&metatag[author]=Jean Carlo Machado&metatag[title]=$title&metatag[description]=$description&metatag[keywords]=$keywords&publicado=0"

curl -X POST -d "$data" $baseUrl/root/post
