#!/bin/bash

posts=`blog-posts 2> /dev/null`
IFSCPY=$IFS
IFS='
'

for i in $posts
do
    id=`echo $i | cut -d"-" -f1`
    id=`trim $id`
    fileName="$id"
    blog-post -i $id --destination ~/posts/$fileName
done

IFS=$IFSCPY
