#!/bin/bash

#ssh -i /home/jean/Dropbox/aws/SAOPAULO.cer ubuntu@ec2-54-207-46-18.sa-east-1.compute.amazonaws.com
ssh -i /home/jean/Dropbox/aws/centos7.pem root@ec2-54-94-203-15.sa-east-1.compute.amazonaws.com
