#!/bin/bash

baseUrl=$BLOG_URL

function getHelp {
    printf "
    saves a post metadata on my blog
    $0 <postId> <full-path-to-file-with-content>
"
}

function isEmpty {
    if [ -z "$1" -o "$1" == " " ]
    then
        echo 1
    else
        echo 0
    fi
}

[ $(isEmpty $@) != 0 ] || [ $(isEmpty $1) != 0 ] || [ $(isEmpty $1) != 0 ] && {
    printf "$(getHelp)"
    exit 0
}

fileWthContent=$2

if [ ! -e $fileWthContent ]; then
    printf "$(getHelp)"
    exit 0
fi

postId=$1

title=`cat $fileWthContent | sed "1q;d" | cut -d'=' -f2`
date=`cat $fileWthContent | sed "2q;d" | cut -d'=' -f2`
published=` cat $fileWthContent | sed "3q;d" | cut -d'=' -f2`
description=` cat $fileWthContent | sed "4q;d" | cut -d'=' -f2`
keywords=` cat $fileWthContent | sed "5q;d" | cut -d'=' -f2`


jsonData='{"data":{"metatags": { "author": "Jean Carlo Machado", "title": "'$title'", "description": "'$description'", "keywords": "'$keywords'"}, "default":{"id":"'$postId'", "titulo":"'$title'", "publicado": "'$published'", "data": "'$date'"}},"parameters":"","id":"'$postId'","action":"save"}'

jsonEncodedData=`echo "$jsonData" | json-urlencode`
jsonEncodedData='ajaxACK='"$jsonEncodedData"

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Connection: keep-alive" -H "Cache-Control: no-cache" -d $jsonEncodedData $baseUrl/posts/routerAjax
