<?php $config = \AckCore\Facade::getInstance()->getControllerConfig(); ?>
<div class="modulo <?= $controllerName ?>">
    <?php \AckCore\HtmlElements\Explain::getInstance()->setName("moduleDescription")->render();?>
    <div class="slide colunas">
        <div class="collumA form">
            <?php
                $elements = \AckCore\DataAbstraction\Service\InterpreterForm::getInstance()->setControllerConfig($config)->buildElementsFromRow($row);
                if(is_array($elements)) {
                    foreach($elements as $element) {
                        $element->render();
                    }
                }
            ?>
        </div><!-- END collumA -->
        <!-- • • • • -->
        <div class="collumB">
            <?php echo $this->visible($row,$disableVisible) ?>
            <?php echo $this->highlight($row,$disableHightlight) ?>
            <?php \AckCore\HtmlElements\LanguageSelector::getInstance()->render() ?>
              <?php
                unset($config["blacklist"]);
                $config["whitelist"] = (isset($colB["whitelist"]) && !empty($colB["whitelist"])) ? $colB["whitelist"] : array();
                $elements =   \AckCore\DataAbstraction\Service\InterpreterForm::getInstance()->setContext(\AckCore\DataAbstraction\Service\InterpreterForm::COL2)->setControllerConfig($config)->buildElementsFromRow($row);
                if(is_array($elements))
                foreach($elements as $element)
                    $element->render();
            ?>
        </div>
        <span class="clearBoth"></span>
    </div><!-- END slide -->
</div><!-- END modulo -->


    <?php
        if($row->getId()->getBruteVal() && class_exists("\AckUsers\Model\Groups") && !empty($Groups)) :
    ?>
    <span class="clearBoth"></span>
    <div class="modulo Groups">
        <?php \AckCore\HtmlElements\Explain::getInstance()->setName("GroupsDescription")->render();?>
     <?php
             $checksGroups = array();
             foreach($Groups as $relationElement) {
                $checksGroups[] = \AckCore\HtmlElements\Check::getInstance(true)
                                                    ->setChecked($relationElement->isChildOf($row,"\AckUsers\Model\GroupsHierarchys", "master_id", "slave_id"))
                                                    ->setTitle($relationElement->getNome()->getBruteVal())
                                                    ->setValue($relationElement->getId()->getBruteVal())
                                                    ->setPermission("+rw")
                                                     ->setUrl("/ack/gruposdeusuarios/editar/".$relationElement->getId()->getBruteVal())
                                                    ->setName("Groups");
             }
              $blockActions = \AckCore\HtmlElements\CheckBlock::getInstance()
              ->setChecks($checksGroups)
              ->setTitle("Grupos que este herda configuraçẽos")
              ->setName("Groups")
              ->setPermission("+rw")
              ->render();
          ?>
    </div>
    <?php endif;
    //###################################################################################
    //################################# END módulo html de relacão NN com Groups ########################################
    //###################################################################################
    ?>
<?php
//###################################################################################
//################################# listagem de módulos ###########################################
//###################################################################################
  if($modules && \AckCore\Facade::getCurrentUser()->hasModulePermission(\AckUsers\Model\Users::moduleId)) :
?>
                <div class="modulo permissoes <?= $row->getId()->getVal() ? "incluir" : "editar" ?>">
                      <?php \AckCore\HtmlElements\Explain::getInstance()->setName("modulePermisson")->render();?>

                    <div class="slide <?= $row->getId()->getVal() ? "incluir" : "editar" ?>">
                        <div class="lista list_permissoes">
                            <div class="header">
                                <span class="borda"></span>
                                <div>
                                    <div class="secao"><button><em>Seção</em></button></div>
                                    <div class="permissao"><button><em>Tipo de permissão</em></button></div>
                                </div>
                                <span class="borda"></span>
                            </div><!-- END header -->
                            <!-- • • • • -->
                            <ol class="listaPermissoes">
                                <?php foreach($modules as $module) : ?>
                                    <li>
                                        <div>
                                            <span class="secao">
                                            <b><?= $module->getTituloPt()->getVal() ?></b>
                                            </span>

                                            <div class="radioGrup">
                                                <label>
                                                    <input type="radio" value="0" name="<?= $module->getId()->getBruteVal() ?>" <?php if(!$module->getUserPermissionLevel($row->getId()->getBruteVal())) { ?> checked="checked" <?php } ?> >
                                                    <em>Não disponível</em>
                                                </label>
                                                <label>
                                                    <input type="radio" value="1" name="<?= $module->getId()->getBruteVal() ?>" <?php if($module->getUserPermissionLevel($row->getId()->getBruteVal()) == 1) { ?> checked="checked" <?php } ?> >
                                                    <em>Somente leitura</em>
                                                </label>
                                                <label>
                                                    <input type="radio" value="2" name="<?= $module->getId()->getBruteVal() ?>" <?php if($module->getUserPermissionLevel($row->getId()->getBruteVal()) == 2) { ?> checked="checked" <?php } ?> >
                                                    <em>Controle completo</em>
                                                </label>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            </ol><!-- END listaPermissoes -->
                        </div><!-- END lista -->
                           <span class="clearBoth"></span>
                    </div><!-- END slide -->
                </div><!-- END modulo -->
<?php
    endif;
//###################################################################################
//################################# END listagem de módulos ########################################
//###################################################################################
?>
