            </div>
                <div acao="carregar_filtro" class="filter-results-options filter-form">
                
                    <div chave="filtros" class="field-block">
                        <div class="filter-results-item titulo">
                            <p class="filter-results-title"><strong>Título</strong></p>

                            <span class="box-list-spacer"></span>

                            <fieldset class="field">
                                <p class="field-text">Título:</p>
                                <label class="placeholder">
                                    <input type="text" autocomplete="off" class="placeholder-input no-valid" name="titulo" />
                                </label>
                            </fieldset>
                        </div>
                
                          <div class="filter-results-item visivel">
                            <p class="filter-results-title"><strong>Vísível</strong></p>

                            <span class="box-list-spacer"></span>

                            <fieldset class="field checkboxGruop">
                                <label class="placeholder">
                                    <input type="checkbox" autocomplete="off" radio="nao_atrasado" class="placeholder-check" name="nao_visivel" />
                                    <p class="field-text">Não Vísível</p>
                                </label>

                                <label class="placeholder">
                                    <input type="checkbox" autocomplete="off" radio="atrasado" class="placeholder-check" name="visivel" />
                                    <p class="field-text">Vísível</p>
                                </label>
                            </fieldset>
                        </div>
                        <button title="Filtrar" class="botao filtro"><span><var></var><em>Filtrar</em></span><var class="borda"></var></button>
                    </div>
