<div class="contactScreen">

<?php $serviceLocator = $this->getHelperPluginManager()->getServiceLocator(); ?>


<input type="hidden" class="pageInfo" data-container='{"rowId":"","urlGateway":"/contatosimples/routerAjax","actionName":"","parameters":""}'/>

<h3>Contato</h3>
<p>Quer entrar em contato comigo? É muito simples! Cadastre seus dados nos campos abaixo, e envie suas ideias, observações, reclamações, dúvidas ou sugestões. Vai ser um prazer conversar com você.</p>
<hr />

<div id="rowContainer">
<?php
//renderiza os elementos principais
$serviceLocator->get('InterpreterForm')->setCustomConfig($contatoConfig)->renderElementsFromRow($this->contatoPrototype);
?>
</div>

<br />

<?php
       $serviceLocator->get('HtmlElementsManager')->getInstanceOf("Button")->setName("save")->appendClass('actionButton')->appendClass('btn')->appendClass('btn-primary')->setValue("Salvar")->setTitle("Enviar mensagem")->setPermission("+rw")->appendTag('data-container','{"dataMinnerMethod":"sendParent","actionName":"contatar"}')->render();
?>
</div>

