<?php
    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();
?>
<div>
    <h3><?php echo $row->getTitulo()->getVal(); ?></h3>

    <div>

        <?php

        $parsedown = new \Parsedown();
        echo $parsedown->text($row->getConteudo()->getVal());

        ?>
    </div>


<div>

    <div>
        <?php
            $serviceLocator->get('HtmlElementsManager')->getInstanceOf('Button')
                ->setName('view-details')
                ->setTitle('Voltar')
                ->setPermission('+rw')
                ->appendClass('btn btn-info')
                ->setUrl($this->url('home', array ('id' => $row->getId()->getVal(), 'title' => $row->getTitulo()->toUrl()->getVal())))
                ->render();

            ?>

    </div>

<div style="position: relative; right: -80px; top: -35px" class="fb-like" data-layout="box_count" data-action="like" data-show-faces="true" data-share="true"></div>

</div>


</div>

<hr />
