<div id="metaTags" class="modulo metaTags">
    <?php \AckCore\HtmlElements\Explain::getInstance()->setName("moduleMetagasDescription")->render();?>

    <div class="slide form" id="metatags">
        <?php
            $meta = ($metatagId) ? \AckCore\Model\Metatags::getFromId($metatagId) : $row->getRelatedMetatags();
        ?>
        <?php echo  \AckCore\HtmlElements\Input::Factory($meta->getTitle(),"Title")->render()?>
        <input type="hidden" <?php if ($metatagsPermissionLevel=="2") { ?>name="id"<?php } else { ?>disabled="disabled"<?php } ?> value="1" />

        <?php echo \AckCore\HtmlElements\Input::Factory($meta->getauthor(),"Author")->render() ?>
        <?php echo \AckCore\HtmlElements\TextArea::Factory($meta->getDescription(),"Description")->render() ?>
        <?php echo \AckCore\HtmlElements\TextArea::Factory($meta->getKeywords(),"Keywords")->render() ?>

        <?php if(isset($metatagsExpansion) && $metatagsExpansion == true) : ?>
        <fieldset id="menuRobot" class="radioGrup">
            <legend><span>Robots</span><div class="ajuda pull-right">
            <span class="ajuda-head" >O que é isso?</span><!-- end ajuda-title -->

            <div class="janelaAjuda" style="display:none;">
                <div class="inner">
                    <div class="inner-head">
                        <span>O que é isso?</span>

                        <i class="icon fechar" data-close=".ajuda-body">x</i>
                    </div><!-- end ajuda-title -->

                    <h5 class="title5">
                        <span>Robots</span>
                    </h5>

                    <div class="text-box">Define como os robôs dos mecanismos de busca devem agir ao ler o conteúdo da página.</div>
                </div>
            </div>
            <!-- end ajuda-body -->
        </div></legend>

            <label>
                <input type="radio" name="robots" value="1"<?php if ($meta->getRobots()->getVal()=="1") {?> checked="checked"<?php } ?> />
                <span><span>INDEX, FOLLOW</span> - Os robôs podem indexar a página e ainda seguir os links para outras páginas que ela contém.</span>
            </label>

            <label>
                <input type="radio" name="robots" value="2"<?php if ($meta->getRobots()->getVal()=="2") {?> checked="checked"<?php } ?> />
                <span><span>INDEX, NOFOLLOW</span> - A página é indexada, mas os links não são seguidos.</span>
            </label>

            <label>
                <input type="radio" name="robots" value="3"<?php if ($meta->getRobots()->getVal()=="3") {?> checked="checked"<?php } ?> />
                <span><span>NOINDEX, FOLLOW</span> - Os links podem ser seguidos, mas a página não é indexada.</span>
            </label>

            <label>
                <input type="radio" name="robots" value="4"<?php if ($meta->getRobots()->getVal()=="4") {?> checked="checked"<?php } ?> />
                <span><span>NOINDEX, NOFOLLOW</span> - A página não é indexada e os links não são seguidos.</span>
            </label>
        </fieldset><!-- END menuRobot -->

         <?php echo \AckCore\HtmlElements\Select::Factory($meta->getRevisit(),"revisitar")->setOption(7,"7 dias")->setOption(15,"15 dias")->setOption(30,"30 dias")->setOption(90,"90 dias")->render() ?>
    <?php endif; ?>
    <span class="clearBoth"></span>
</div><!-- END slide -->
</div><!-- END modulo  -->
