</section>


<footer class="container hidden-print">
	<div class="row">
		<div class="col-xs-12">
			<div class="well">
				<div class="row">
					<div class="col-xs-12 col-md-6 col-md-push-6">
                    <a href="#topo" class="hidden-md hidden-lg">Topo&nbsp;<span class="glyphicon glyphicon-circle-arrow-up"></span></a>
                    </div>

                    <br />
                    <div class="row-fluid col-xs-12 col-md-6 col-md-pull-6 span6">

                    <div class="col-xs-12 col-md-6 col-md-pull-6 span6">
                        © 2014 Jean Carlo Machado
                        <a href="<?php echo $this->url('sobre'); ?>">Sobre</a> 
                        <a href="<?php echo $this->url('contatar'); ?>">Contato</a> 
                        <a href="<?php echo $this->url('login'); ?>">Entrar</a>

                    </div>
                    
                    </div>
				</div>
			</div>
		</div>
	</div>
</footer>
</body>
</html>
