<footer class="container hidden-print">
                    <a href="#topo" class="hidden-md hidden-lg">Topo&nbsp;<span class="glyphicon glyphicon-circle-arrow-up"></span></a>
                    </div>
                        <a href="<?php echo $this->url('sobre'); ?>">Sobre</a> |
                        <a target="_blank" href="https://github.com/jeanCarloMachado">Github</a> |
                        <a target="_blank" href="http://www.linkedin.com/pub/jean-carlo-machado/77/159/53b">LinkedIn</a> |
                        <a target="_blank" href="https://twitter.com/JeanCarloMachad">Twitter</a> |
                        <a target="_blank" href="http://stackoverflow.com/users/3344920/jean-carlo-machado">StackOverflow</a> |
                        <a href="<?php echo $this->url('contatar'); ?>">Contato</a> |
                        <a href="<?php echo $this->url('login'); ?>">Entrar</a> |
                    © 2014 Jean Carlo Machado
</footer>

</body>
</html>
