<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/bootstrap.min.css', 'all');

//Twitter Bootstrap theme style
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/bootstrap-theme.min.css', 'all');

// JQuery UI
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/smoothness/jquery-ui-1.10.3.custom.min.css');
$this->headLink()->appendStylesheet($basePath . '/plugins/colorbox-master/colorbox.css');



//Add your own style here
//$this->headLink()->appendStylesheet($basePath . '/css/style.css');

$this->headLink()->appendStylesheet($basePath . '/site-jean/css/style.site.css', 'all');
?>

<?php
//jQuery and Twitter Bootstrap JS libraries

$this->inlineScript()->offsetSetFile(1, $basePath . '/site-jean/js/jquery-1.10.2.min.js');
$this->inlineScript()->offsetSetFile(2, $basePath . '/site-jean/js/jquery-migrate-1.2.1.min.js');
$this->inlineScript()->offsetSetFile(3, $basePath . '/site-jean/js/jquery-ui-1.10.3.custom.min.js');
$this->inlineScript()->offsetSetFile(4, $basePath . '/site-jean/js/jquery.ui.datepicker-pt-BR.js');
$this->inlineScript()->offsetSetFile(5, $basePath . '/site-jean/js/bootstrap.min.js');
$this->inlineScript()->offsetSetFile(6, $basePath . '/plugins/colorbox-master/jquery.colorbox-min.js');
//espaço para o tinymce (opcional)

$this->inlineScript()->offsetSetFile(8, $basePath . '/site-jean/js/devil.js');
$this->inlineScript()->offsetSetFile(9, $basePath . '/site-jean/js/script.site.js');
?>
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>

    <?php $this->Metatags(); ?>
    <!-- Scripts -->
    <script type="text/javascript">
        var basePath = "<?php echo ($this->basePath()) ? $this->basePath() : '/'; ?>";
    </script>
    <?php echo $this->headScript() ?>
<?php echo $this->inlineScript(); ?>

<link href="<?php echo $this->basePath() ?>/favicon.ico" rel="icon" type="image/x-icon" />
</head>
