<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/bootstrap.min.css', 'all');


$this->headLink()->appendStylesheet($basePath . '/site-jean/css/style.site.css', 'all');
?>

<?php
//jQuery and Twitter Bootstrap JS libraries

$this->inlineScript()->offsetSetFile(1, $basePath . '/site-jean/js/jquery-1.10.2.min.js');
$this->inlineScript()->offsetSetFile(2, $basePath . '/site-jean/js/jquery-migrate-1.2.1.min.js');
$this->inlineScript()->offsetSetFile(3, $basePath . '/site-jean/js/jquery-ui-1.10.3.custom.min.js');
$this->inlineScript()->offsetSetFile(4, $basePath . '/site-jean/js/jquery.ui.datepicker-pt-BR.js');
$this->inlineScript()->offsetSetFile(5, $basePath . '/site-jean/js/bootstrap.min.js');
$this->inlineScript()->offsetSetFile(6, $basePath . '/plugins/colorbox-master/jquery.colorbox-min.js');
//espaço para o tinymce (opcional)

$this->inlineScript()->offsetSetFile(8, $basePath . '/site-jean/js/devil.js');
$this->inlineScript()->offsetSetFile(9, $basePath . '/site-jean/js/script.site.js');
?>
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <link href="http://www.jeancarlomachado.com.br/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <link href='http://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <?php echo $this->headStyle(); ?>


    <?php

        if (!isset($row)) {
            $row = (isset($config['row'])) ? $config['row'] : null;
        }
        $this->Metatags($row);
    ?>
    <!-- Scripts -->
    <script type="text/javascript">
        var basePath = "<?php echo ($this->basePath()) ? $this->basePath() : '/'; ?>";
    </script>
    <?php echo $this->headScript() ?>
<?php echo $this->inlineScript(); ?>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49232964-1', 'jeancarlomachado.com.br');
  ga('send', 'pageview');

</script>
</head>
