<?php require_once __DIR__ . '/head.phtml'; ?>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1402355320025389";
      fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


	<section role="main" class="container">

		<div id="topo" class="row">
			<div class="col-xs-12 col-md-4">

            <a href="http://jeancarlomachado.com.br"><h1>Vida de backend</h1></a>

            <p> Um blog para registrar algumas experiências de um desconhecido programador backend. Posts sobre PHP, Zend Framework, Linux, eletrônica, filosofia entre outros. </p>
            </div>
            <div class="col-xs-12 col-md-8">
                <br class="visible-md visible-lg" />
                <br class="visible-md visible-lg" />
                <h1></h1>
            </div>



		</div>

		<!-- Menu de informações genéricas do sistema importantes para o usuário as quais devem permanecer em todas as páginas -->
		<?php echo $this->partial("/site-jean/layout/partials/mainMenu.phtml"); ?>



        <?php

            $messages = (isset($messages)) ? $messages : array();

            $notifications = $this->notificationBlock($messages);
            if ($notifications->hasMessages()):
        ?>
                <div class="row">
                    <div class="col-xs-12 hidden-print">
                    <?php
                        echo $notifications->render();
                    ?>
                    </div>
                </div>
        <?php endif; ?>
