<?php require_once __DIR__ . '/head.phtml'; ?>

<body>
	<section role="main" class="container">

		<div id="topo" class="row">
			<div class="col-xs-12 col-md-4">

                <a href="http://jeancarlomachado.com.br"><h4>Jean Carlo Machado</h4></a>
                <p> Um blog para registrar algumas experiências de um <s>desconhecido</s> programador backend. Posts sobre programação em geral, PHP, Zend Framework, Linux, eletrônica, filosofia e qualquer outra coisa, a meu julgamento, relevante. </p>
            </div>
            <div class="col-xs-12 col-md-8">
                <br class="visible-md visible-lg" />
                <br class="visible-md visible-lg" />
            </div>
		</div>

		<?php echo $this->partial("/site-jean/layout/partials/mainMenu.phtml"); ?>

        <?php

            $messages = (isset($messages)) ? $messages : array();

            $notifications = $this->notificationBlock($messages);
            if ($notifications->hasMessages()):
        ?>
                <div class="row">
                    <div class="col-xs-12 hidden-print">
                    <?php
                        echo $notifications->render();
                    ?>
                    </div>
                </div>
        <?php endif; ?>
