<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckProducts\Module'                                    => __DIR__ . '/Module.php',
    'AckProducts\Model\Services'                            => __DIR__ . '/src/AckProducts/Model/Services.php',
    'AckProducts\Model\CategorysHierarchy'                  => __DIR__ . '/src/AckProducts/Model/CategorysHierarchy.php',
    'AckProducts\Model\Product'                             => __DIR__ . '/src/AckProducts/Model/Product.php',
    'AckProducts\Model\ProductsCategory'                    => __DIR__ . '/src/AckProducts/Model/ProductsCategory.php',
    'AckProducts\Model\ProdutosComponente'                  => __DIR__ . '/src/AckProducts/Model/ProdutosComponente.php',
    'AckProducts\Model\ProductsComponents'                  => __DIR__ . '/src/AckProducts/Model/ProductsComponents.php',
    'AckProducts\Model\Categorys'                           => __DIR__ . '/src/AckProducts/Model/Categorys.php',
    'AckProducts\Model\CategorysHierarchys'                 => __DIR__ . '/src/AckProducts/Model/CategorysHierarchys.php',
    'AckProducts\Model\Products'                            => __DIR__ . '/src/AckProducts/Model/Products.php',
    'AckProducts\Model\ProdutosComponentes'                 => __DIR__ . '/src/AckProducts/Model/ProdutosComponentes.php',
    'AckProducts\Model\Service'                             => __DIR__ . '/src/AckProducts/Model/Service.php',
    'AckProducts\Model\ProductsCategorys'                   => __DIR__ . '/src/AckProducts/Model/ProductsCategorys.php',
    'AckProducts\Model\Category'                            => __DIR__ . '/src/AckProducts/Model/Category.php',
    'AckProducts\Model\ProductsComponent'                   => __DIR__ . '/src/AckProducts/Model/ProductsComponent.php',
    'AckProducts\Controller\ServicosController'             => __DIR__ . '/src/AckProducts/Controller/ServicosController.php',
    'AckProducts\Controller\CategoriasdeprodutosController' => __DIR__ . '/src/AckProducts/Controller/CategoriasdeprodutosController.php',
    'AckProducts\Controller\ProdutosController'             => __DIR__ . '/src/AckProducts/Controller/ProdutosController.php',
);
