<?php $container = $this->navigation()->breadcrumbs();  ?>
<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php $navigation = $container->getContainer();

?>
<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
    <?php $active = $container->findActive($navigation);
    ?>
    <?php foreach($this->pages as $page): ?>
        <?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
        <?php if( ! $page->isActive()): ?>
            <li>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
            </li>
        <?php else: ?>
            <li class="active">
                <?php echo $page->getLabel(); ?>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
