<?php echo $this->headTitle() ?>
<?php echo $this->content; ?>
<?php if(isset($disableFooter) && $disableFooter == true) die; ?>
<?php if ($permissionLevel=="2" && $plugins )
echo $this->partial("/ack-core/layout/default/partials/multimidia.phtml",array(
                                                                              "row"=>$row,
                                                                              "abaImagens"=>$abaImagens,
                                                                              "abaVideos"=>$abaVideos,
                                                                              "abaAnexos" =>$abaAnexos,
                                                                              "tamanhoCrop" => $tamanhoCrop,
                                                                              "multiplasImagens" => $multiplasImagens


                                                                              ));
?>
<?php if ($metatagsPermissionLevel || $metatags )
echo $this->partial("/ack-core/layout/default/partials/metatags.phtml",array("row"=>$row,
                                                                              "metatagId"=>$metatagId,
                                                                              "metatagsExpansion"=>$metatagsExpansion,
                                                                              "metatagsPermissionLevel"=>$metatagsPermissionLevel
                                                                            ));
?>
<?php if($idiomas) echo $this->partial("/ack-core/layout/default/partials/idioms.phtml"); ?>

</div><!-- END parentFull -->

<?php if(isset($row)) : ?>

<!-- • • • • -->
  <div id="footerPage">
    <?php if(!isset($disableBack)) : ?>
    <a href="/ack/<?php echo $controllerName ?>" class="btnSeta voltarTopo" title="Voltar">Voltar</a>
  <?php endif; ?>
  <?php
    if(isset($footerElements) && !empty($footerElements)) foreach($footerElements as $element)  $element->render();
  ?>

<?php if(!isset($disableSave)) : ?>
  <button class="botao salvar" name="<?= ($row->getId()->getBruteVal() ? "editar" : "incluir") ?>" title="Salvar" id="salvar<?= $controllerName?>"><span><var></var><em>Salvar</em></span><var class="borda"></var></button>
<?php endif; ?>

</div><!-- END footerPage -->
<?php endif; ?>
