
<!-- sujeito a virar partial -->
</div><!-- END wrappeACK-content -->

<div class="borda fundo"></div>
</div><!-- END wrappeACK -->
    <hr />
    <div class="menuInfo fundo">
        <ul>
            <li><p>© ACK<?php echo \AckCore\Facade::getAckVersion(); ?> - Todos os direitos reservados.</p></li>
            <li class="separador">|</li>
            <li><a href="/ack/textos/termos" title="Termos de Uso">Termos de Uso</a></li>
            <li class="separador">|</li>
            <li><a href="/ack/textos/privacidade" title="Política de privacidade">Política de privacidade</a></li>
        </ul>

        <em id="assCUB">desenvolvido por <a href="http://www.icub.com.br" target="_blank" title="CUB">CUB</a></em>
    </div>

</div><!-- END wrapper -->
</body>
</html>
