<?php

//pega o viewmodel do controlador
$children = $this->viewModel()->getCurrent()->getChildren();
$child = reset($children);
if ($child) {
    $variables = $child->getVariables();
    if(is_object($variables)) {
        extract($variables->getArrayCopy());
    }
}

$this->headTitle()->setSeparator(' - ')
    ->setAutoEscape(false);
$basePath = $this->basePath();

$this->headLink()->appendStylesheet($basePath . '/site-jean/css/bootstrap.min.css', 'all');
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/style.site.css', 'all');
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <link href="<?php echo $basePath ?>/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <link href='http://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
<?php echo $this->headLink() ?>
<?php echo $this->headStyle(); ?>

<?php
if (!isset($row)) {
    $row = (isset($config['row'])) ? $config['row'] : null;
}
$this->Metatags($row);
?>


<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-49232964-1', 'jeancarlomachado.com.br');
ga('send', 'pageview');
</script>
</head>

<body>
    <section role="main" class="container">
        <div id="topo" class="row">
            <div class="col-xs-12 col-md-4">
                <a href="javascript:void(0);"><h4>Jean Carlo Machado</h4></a>
                <p>This is my blog. Here you will find about science, technology, the open source world, the Unix way, my opinions, etc.</p>
            </div>
            <div class="col-xs-12 col-md-8">
                <br class="visible-md visible-lg" />
                <br class="visible-md visible-lg" />
            </div>
        </div>

<?php echo $this->partial("/site-jean/layout/partials/mainMenu.phtml"); ?>

<?php

$messages = (isset($messages)) ? $messages : array();

$notifications = $this->notificationBlock($messages);
if ($notifications->hasMessages()):
?>
                <div class="row">
                    <div class="col-xs-12 hidden-print">
<?php
    echo $notifications->render();
?>
                    </div>
                </div>
        <?php endif; ?>

<?php echo $this->content; ?>

<footer class="container hidden-print">
                <a href="#topo" class="hidden-md hidden-lg">Top&nbsp;<span class="glyphicon glyphicon-circle-arrow-up"></span></a>
                <a target="_blank" href="<?php echo $basePath?>/feed">Feed</a> |
                    <a href="<?php echo $this->url('sobre'); ?>">About</a> |
                    <a target="_blank" href="https://github.com/jeanCarloMachado">Github</a> |
                    <a target="_blank" href="http://www.linkedin.com/pub/jean-carlo-machado/77/159/53b">LinkedIn</a> |
                    <a target="_blank" href="https://twitter.com/JeanCarloMachad">Twitter</a> |
                    <a target="_blank" href="http://stackoverflow.com/users/3344920/jean-carlo-machado">StackOverflow</a> |
                    <a href="<?php echo $this->url('login'); ?>">Entrar</a> |
                © 2014 Jean Carlo Machado
</footer>

    </section>
</body>
</html>


