<?php $this->layout()->setTemplate('error/404'); ?>
<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/bootstrap.min.css', 'all');

//Twitter Bootstrap theme style
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/bootstrap-theme.min.css', 'all');

// JQuery UI
$this->headLink()->appendStylesheet($basePath . '/site-jean/css/smoothness/jquery-ui-1.10.3.custom.min.css');
$this->headLink()->appendStylesheet($basePath . '/plugins/colorbox-master/colorbox.css');



//Add your own style here
//$this->headLink()->appendStylesheet($basePath . '/css/style.css');

$this->headLink()->appendStylesheet($basePath . '/site-jean/css/style.site.css', 'all');
?>

<?php
//jQuery and Twitter Bootstrap JS libraries

$this->inlineScript()->offsetSetFile(1, $basePath . '/site-jean/js/jquery-1.10.2.min.js');
$this->inlineScript()->offsetSetFile(2, $basePath . '/site-jean/js/jquery-migrate-1.2.1.min.js');
$this->inlineScript()->offsetSetFile(3, $basePath . '/site-jean/js/jquery-ui-1.10.3.custom.min.js');
$this->inlineScript()->offsetSetFile(4, $basePath . '/site-jean/js/jquery.ui.datepicker-pt-BR.js');
$this->inlineScript()->offsetSetFile(5, $basePath . '/site-jean/js/bootstrap.min.js');
$this->inlineScript()->offsetSetFile(6, $basePath . '/plugins/colorbox-master/jquery.colorbox-min.js');
//espaço para o tinymce (opcional)

$this->inlineScript()->offsetSetFile(8, $basePath . '/site-jean/js/devil.js');
$this->inlineScript()->offsetSetFile(9, $basePath . '/site-jean/js/script.site.js');
?>
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <link href="http://www.jeancarlomachado.com.br/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>

    <!-- Scripts -->
    <script type="text/javascript">
        var basePath = "<?php echo ($this->basePath()) ? $this->basePath() : '/'; ?>";
    </script>
    <?php echo $this->headScript() ?>
<?php echo $this->inlineScript(); ?>

</head>
<body>

<div class="container">
  <div class="row">
    <div class="span12">
      <div class="hero-unit center">
          <h1>Page Not Found <small><font face="Tahoma" color="red">Error 404</font></small></h1>
          <br />
          <p>The page you requested could not be found, either contact your webmaster or try again. Use your browsers <b>Back</b> button to navigate to the page you have prevously come from</p>
          <p><b>Or you could just press this neat little button:</b></p>
          <a href="<?php echo $this->url('home') ?>" class="btn btn-large btn-info"><i class="icon-home icon-white"></i> Take Me Home</a>
        </div>
        <br />
  </div>
</div>
</body>
</html>

