
     <div class="collumA lista">
                            <div class="header">
                                <span class="borda"></span>
                                <div>
                                      <div class="coluna_id 50 txt"><button><em>ID Log</em></button></div>
                                    <div class="data 75 txt"><button><em>Data e Hora</em></button></div>
                                    <div class="texto_log 510 txt"><button><em>Mensagam</em></button></div>
                                </div>
                                <span class="borda"></span>
                            </div><!-- END header -->

                            <ol></ol>
                            <div class="clearButh"></div>

                            <button class="carregarMais list-logs" title="Carregar mais resultados" name="destaques"><span class="borda esq"></span><em>Exibir mais resultados</em><span class="borda dir"></span></button>
                        </div><!-- END lista -->

                        <!-- • • • • -->

                        <div class="collumB form">
                            <fieldset>
                                <div class="legend"><em>Usuário</em></div>

                                <div class="select usuarios">
                                    <select id="usuarios">
                                        <option value="">Todos</option>
	                                        <?php
                                                    $modelUsers = new \AckUsers\Model\Users;
                                                    $users = $modelUsers->toObject()->onlyNotDeleted()->get(array("acesso_ack" => 1));
	                                        foreach ($users as $user) :
	                                        ?>
	                                        <option value="<?= $user->getId()->getBruteVal() ?>"><?= $user->getNome()->getVal() ?></option>
	                                        <?php
	                                        endforeach;
	                                        ?>
                                    </select>
                                </div>
                            </fieldset>

                            <fieldset>
                                <div class=legend><em>Período</em></div>

                                <div class="select periodo">
                                    <select id="periodo">
                                        <option value="">Completo</option>
                                        <option value="3">Últimos 3 dias</option>
                                        <option value="15">Últimos 15 dias</option>
                                        <option value="30">Últimos 30 dias</option>
                                        <option value="60">Últimos 60 dias</option>
                                        <option value="180">Últimos 180 dias</option>
                                    </select>
                                </div>
                            </fieldset>
                        </div><!-- END collumB -->
                        </div></div>
