<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckCmd\Module'                         => __DIR__ . '/Module.php',
    'AckCmd\Controller\HelpController'      => __DIR__ . '/src/AckCmd/Controller/HelpController.php',
    'AckCmd\Controller\MvcController'       => __DIR__ . '/src/AckCmd/Controller/MvcController.php',
    'AckCmd\Controller\IndexController'     => __DIR__ . '/src/AckCmd/Controller/IndexController.php',
    'AckCmd\Controller\TranslateController' => __DIR__ . '/src/AckCmd/Controller/TranslateController.php',
);
