<?php
    $config = \AckCore\Facade::getInstance()->getControllerConfig();
?>
<div class="modulo <?= $controllerName ?>">
    <?php \AckCore\HtmlElements\Explain::getInstance()->setName("moduleDescription")->render();?>

    <div class="slide colunas">
        <div class="collumA form">
            <?php
                $automator = new \AckCore\HtmlElements\Automator;
                $automator->getProperColumns($row,$config);
            ?>

            <?php
                $select = \AckCore\HtmlElements\Select::getInstance()->setName("categoria_id")->setTitle("Categoria de Faq")->setPermission('r')->setValue($row->getCategoriaId()->getBruteVal());

                $select->setOption(0,"Selecione");
                foreach($FaqCategorys as $category) {
                    $checked = ($row->getCategoriaId()->getBruteVal() == $category->getId()->getBruteVal()) ? true : false;
                    $select->setOption($category->getId()->getBruteVal(),$category->getNome()->getVal(),$checked);
                }

                $select->render();
            ?>
        </div><!-- END collumA -->
        <!-- • • • • -->
        <div class="collumB">
            <?php echo $this->visible($row,$disableVisible) ?>
            <?php
            \AckCore\HtmlElements\LanguageSelector::getInstance()->render() ?>

              <?php
                $automator = new \AckCore\HtmlElements\Automator;
                unset($config["blacklist"]);
                $config["whitelist"] = (is_array($colB["whitelist"])) ? $colB["whitelist"] : array();
                $automator->getProperColumns($row,$config);
            ?>
        </div>
    </div><!-- END slide -->
</div><!-- END modulo -->
