<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckLocale\Module'                         => __DIR__ . '/Module.php',
    'AckLocale\Model\Countrys'                 => __DIR__ . '/src/AckLocale/Model/Countrys.php',
    'AckLocale\Model\Addresses'                => __DIR__ . '/src/AckLocale/Model/Addresses.php',
    'AckLocale\Model\Country'                  => __DIR__ . '/src/AckLocale/Model/Country.php',
    'AckLocale\Model\States'                   => __DIR__ . '/src/AckLocale/Model/States.php',
    'AckLocale\Model\State'                    => __DIR__ . '/src/AckLocale/Model/State.php',
    'AckLocale\Model\City'                     => __DIR__ . '/src/AckLocale/Model/City.php',
    'AckLocale\Model\Address'                  => __DIR__ . '/src/AckLocale/Model/Address.php',
    'AckLocale\Model\Citys'                    => __DIR__ . '/src/AckLocale/Model/Citys.php',
    'AckLocale\Controller\CidadesController'   => __DIR__ . '/src/AckLocale/Controller/CidadesController.php',
    'AckLocale\Controller\EnderecosController' => __DIR__ . '/src/AckLocale/Controller/EnderecosController.php',
    'AckLocale\Controller\EstadosController'   => __DIR__ . '/src/AckLocale/Controller/EstadosController.php',
    'AckLocale\Controller\PaisesController'    => __DIR__ . '/src/AckLocale/Controller/PaisesController.php',
);
