<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckBlog\Module'                        => __DIR__ . '/Module.php',
    'AckBlog\Model\NewRow'                  => __DIR__ . '/src/AckBlog/Model/NewRow.php',
    'AckBlog\Model\News'                    => __DIR__ . '/src/AckBlog/Model/News.php',
);

