#! /bin/bash
varDate=$(date)
varMessageDef="Mensagem padrão do script de commit - data: $varDate"
varDir=$(pwd)

echo "Efetuando pull, diretório atual: $varDir "
git pull origin master
echo "Efetuando o add . "
git add .
# pega a mensagem do commit do usuário
read -p "mensagem do commit default <$varMessageDef>" varMessage

if [[ ! $varMessage ]]; then
        varMessage=$varMessageDef
fi

git commit -m "$varMessage" -a
echo "fazendo o push"
git push origin master
