<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckUsers\Module'                        => __DIR__ . '/Module.php',
    'AckUsers\Model\User'                    => __DIR__ . '/src/AckUsers/Model/User.php',
    'AckUsers\Model\Users'                   => __DIR__ . '/src/AckUsers/Model/Users.php',
    'AckUsers\Model\Permissions'             => __DIR__ . '/src/AckUsers/Model/Permissions.php',
    'AckUsers\Model\Permission'              => __DIR__ . '/src/AckUsers/Model/Permission.php',
    'AckUsers\Controller\UsuariosController' => __DIR__ . '/src/AckUsers/Controller/UsuariosController.php',
    'AckUsers\Auth\User'                     => __DIR__ . '/src/AckUsers/Auth/User.php',
);
