<?php $config = \AAckCore\Facade::getInstance()->getControllerConfig(); ?>
<div class="modulo <?= $controllerName ?>">
    <?php \System\HtmlElements\Explain::getInstance()->setName("moduleDescription")->render();?>
    <div class="slide colunas">
        <div class="collumA form blockFinishTask">
            <input type="hidden"  name="id" value="<?php echo  $row->getId()->getBruteVal(); ?>" />
            <?php
                $automator = new \System\HtmlElements\Automator;
                $automator->getProperColumns($row,$config);
            ?>
        </div><!-- END collumA -->
        <!-- • • • • -->
        <div class="collumB">
            <?php echo $this->visible($row,$disableVisible) ?>
            <?php \System\HtmlElements\LanguageSelector::getInstance()->render() ?>
              <?php
                $automator = new \System\HtmlElements\Automator;
                unset($config["blacklist"]);
                $config["whitelist"] = (isset($colB["whitelist"]) && !empty($colB["whitelist"])) ? $colB["whitelist"] : array();
                $automator->getProperColumns($row,$config);
            ?>
            <?php
                // \System\HtmlElements\Button::getInstance()->setPermission("+rw")->setName("concluir")->setTitle("Concluir tarefa")->setAjaxBlockName("blockFinishTask")->setAjaxAction("finishTask")->render();
            ?>
        </div>
    </div><!-- END slide -->
</div><!-- END modulo -->

<?php
//###################################################################################
//################################# TasksHistory##########################################
//###################################################################################
//o módulo só é mostrado caso seja um editar
if($row->getId()->getBruteVal()) :
?>
    <span class="clearBoth"></span>
    <div class="modulo TasksHistory">
       <?php \System\HtmlElements\Explain::getInstance()->setName("TasksHistoryDescription")->setTitle("Histórico da atividade")->render();?>

       <?php
         foreach($TasksHistory as $taksH) {
            $userId = ($taksH->getUsuarioId()->getBruteVal()) ? $taksH->getUsuarioId()->getBruteVal() : \AckAgenda\Model\Tasks::DEFAULT_USER_ID;
            $user = \AckUsers\Model\Users::getFromId($userId);
            $userConcluded = ($taksH->getUsuarioConcluinteId()->getBruteVal()) ? $taksH->getUsuarioConcluinteId()->getBruteVal() : \AckAgenda\Model\Tasks::DEFAULT_USER_ID;
            $userConcluded = \AckUsers\Model\Users::getFromId($userConcluded);
             \System\HtmlElements\Lista::getInstance()->setPermission("+r")->setName("lista-log")->setTitle("asdf")->addEntry(
                "Data",$taksH->getData()->getBruteVal())->addEntry("Usuário responsável",$user->getNome()->getBruteVal())->addEntry("Usuário que concluiu",$userConcluded->getNome()->getBruteVal())->render();
         }
        ?>
    </div>
<?php
endif;
//###################################################################################
//################################# END TasksHistory########################################
//###################################################################################
?>
