<?php
//pega o service locator através do helperPluginManager do layout
$auth = $this->getHelperPluginManager()->getServiceLocator()->get('auth');
$backUser = $auth->getIdentity();

?>

<div class="parentFull" id="dashboard">
  <a href="" target="_blank" title="Visite o site" id="preview"><span></span><img src="/<?php echo \AckCore\Facade::getPublicFolderOfMainModule(); ?>/imagens/thumbAck.jpg" width="364" height="224" alt="preview do site" /></a>

    <!-- • • • • -->

    <div class="modulo Wfull" id="dadosSite">
      <?php if ($backUser->getPrimeiraSenha()->getBruteVal()=="1") : ?>
      <div class="alerta">
            <span></span>
            <div>
                <img src="/ack-core/images/icon_alerta.png" width="24" height="24" alt="(ALERTA)" />
                <p>Para sua segurança, você deve alterar a sua senha. <a href="/ack/usuarios/editar/<?php echo $backUser->getId()->getBruteVal() ?>" title="Editar senha">Clique aqui</a>.</p>
                <a href="javascript:void(0);" title="Fechar">(X)</a>
            </div>
            <span></span>
        </div><!-- END alerta -->
        <?php endif; ?>
        <!-- • • • • -->
        <h2>Informações gerais</h2>
        <?php
        $log = \AckCore\View\Helper\LogsInfo::lastChangeObject();
        ?>
        <!-- • • • • -->
        <ul>
        	<li>Data de publicação:           <var><?php echo $this->info()->getDataPublicacao() ?></var>.</li>
        	<li>Última atualização:               <var><?php echo $log->getData()->getVal() ?></var> pelo usuário <var><?php echo $log->getUsuarioObject()->getNome()->getVal() ?> </var>.</li>
        	<li>Número de visitas do site no mês: <var><?= $this->info()->totalVisitsThisMonth() ?></var></li>
        	<li>Total de visitas do site:         <var><?php echo $this->info()->totalVisits() ?></var></li>
        	<li>Média mensal de visitas:          <var><?php echo $this->info()->totalVisitsAverage(); ?></var></li>
            <?php if(class_exists('\AckProducts\Model\ProductsCategorys')) : ?>
           <li>Categorias de produtos:           <var><?php echo \AckProducts\Model\ProductsCategorys::getTotal() ?></var></li>
            <?php endif; ?>
            <?php if(class_exists('\AckProducts\Model\Products')) : ?>
             <li>Produtos cadastrados:             <var><?php echo \AckProducts\Model\Products::getTotal() ;?></var></li>
           <?php endif; ?>
            <?php if(class_exists('\AckContact\Model\Contacts')) : ?>
           <li>Novos contatos:                   <var><?php echo \AckContact\Model\Contacts::newContactsNum() ?></var></li>
           <?php endif; ?>
       </ul>

       <!-- • • • • -->
       <p>Relatório completo: <a href="http://www.google.com.br/analytics" target="_blank" title="Google Analytics">Google Analytics</a></p>
       <p>Visualizar o site: <a href="<?php echo \AckCore\Facade::getEnderecoSite(); ?>" target="_blank" title=""><?php echo \AckCore\Facade::getEnderecoSite(); ?></a></p>
