<?php require_once __DIR__."/partials/head.phtml"; ?>
<body>
<?php echo $this->partial("/ack-core/layout/default/partials/systemInfo.phtml",array("controllerName"=>$controllerName,"row"=>$row,"moduleName" => $moduleName));?>

<?php echo $this->partial("/ack-core/layout/default/partials/infoMenu.phtml"); ?>

<?php echo $this->partial("/ack-core/layout/default/partials/navigationMenu.phtml"); ?>

<?php
echo $this->partial("/ack-core/layout/default/partials/breadCrumbs.phtml",array(
                                                                                    "controllerName"=>$controllerName,
                                                                                    "title"=>$title,"disableBackButtons"=>$disableBackButtons,
                                                                                    "disableTitlePluralizer" => $disableTitlePluralizer,
                                                                                    "disableBreadcrumbs" => $disableBreadcrumbs
                                                                                ));
?>

<?php \AckCore\HtmlElements\Explain::getInstance()->setName("mainDescription")->setLayoutType(2)->render();?>

<!-- marcação de início de negócio -->
<?php if(!isset($disableAutoParentFull)) : ?>
    <div class="parentFull<?php echo isset($parentFullClassess) ? " ".$parentFullClassess : "" ?>" <?php echo isset($parentFullId) ? 'id="'.$parentFullId.'"' : "" ?>>
<?php endif; ?>
