<?php
    $serviceLocator = $this->getHelperPluginManager()->getServiceLocator();

    $visits = $serviceLocator->get('AckCore\Model\Visits');
    $contacts = $serviceLocator->get('Contacts');
    $posts = $serviceLocator->get('Posts');
?>
<div class="row">
	<div class="col-xs-12">
		<div class="jumbotron">
			<!-- TODO: Form aqui -->
            <!-- lista da esquerda -->
                  <ul>
                        <li>
                            Total de visitas do site:
                            <var><?php echo (int) $visits->getTotal() ?></var></li>
                        </li>
                        <li>
                            Total de visitas hoje:
                            <var><?php echo $visits->getTotalForDate(new \Datetime('now')) ?></var>
                        </li>
                        <li>
                            Média de vistas por post:
                            <var><?php echo (int) ($visits->getTotal() / $posts->count()) ?></var></li>
                        <li>

                            Total de contatos:
                            <var><?php echo (int) $contacts->count(); ?></var>
                        </li>
                        <li>
                            Total de posts:
                            <var><?php echo (int) $posts->count(); ?></var>
                        </li>
                        <li>
                            Total de posts publicados:
                            <var><?php echo (int) $posts->getTotalPubished(); ?></var>
                        </li>

                        <li>
                            Percentual de posts publicados:
                            <var><?php echo (int) $posts->getPublishedAverage(); ?>%</var>
                        </li>

                  </ul>
		</div>
	</div>
</div>
