<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AckDevel\Module'                            => __DIR__ . '/Module.php',
    'AckDevel\Model\Teste'                       => __DIR__ . '/src/AckDevel/Model/Teste.php',
    'AckDevel\Model\Dashboards'                  => __DIR__ . '/src/AckDevel/Model/Dashboards.php',
    'AckDevel\Model\Testes'                      => __DIR__ . '/src/AckDevel/Model/Testes.php',
    'AckDevel\Model\SettingsUsers'               => __DIR__ . '/src/AckDevel/Model/SettingsUsers.php',
    'AckDevel\Model\DatabaseScriptss'            => __DIR__ . '/src/AckDevel/Model/DatabaseScriptss.php',
    'AckDevel\Model\Dashboard'                   => __DIR__ . '/src/AckDevel/Model/Dashboard.php',
    'AckDevel\Model\SettingsUser'                => __DIR__ . '/src/AckDevel/Model/SettingsUser.php',
    'AckDevel\Model\DatabaseScripts'             => __DIR__ . '/src/AckDevel/Model/DatabaseScripts.php',
    'AckDevel\Controller\ConfusuariosController' => __DIR__ . '/src/AckDevel/Controller/ConfusuariosController.php',
    'AckDevel\Controller\TestesController'       => __DIR__ . '/src/AckDevel/Controller/TestesController.php',
    'AckDevel\Controller\ScriptsbancoController' => __DIR__ . '/src/AckDevel/Controller/ScriptsbancoController.php',
    'AckDevel\Controller\DashboardController'    => __DIR__ . '/src/AckDevel/Controller/DashboardController.php',
);
