<?php
    require_once \AckCore\Facade::getPublicPath()."/../module/AckCore/view/ack-core/default/element.phtml";
?>
<div class="modulo controllers">
<?php
  $defaultPermission = \AckCore\HtmlElements\ElementAbstract::LESSER_EDITABLE_PERMISSION;
  $actions = array();
  $checks = array();
  foreach($controllers as $controller) {
    $checks[] = \AckCore\HtmlElements\Check::getInstance(true)
                                        ->setChecked($row->isChecked($controller))
                                        ->setTitle($controller)
                                        ->setValue($controller)
                                        ->setPermission($defaultPermission)
                                        ->setName("controllers");
    if(class_exists($controller)) {

        try{
            $controller = new $controller;
            foreach($controller->getActions() as $action) {
              $actions[$action]  = $action;
            }
          } catch (\Exception $e) {

          }
      }
  }
  $block = \AckCore\HtmlElements\CheckBlock::getInstance()->setChecks($checks)
  ->setTitle("Controllers")
  ->setName("blocoController")
  ->setPermission($defaultPermission)
  ->render();
?>
</div>
<span class="clearBoth"></span>

<div class="modulo actions">
 <?php

        $checkedActions = unserialize($row->getAcoes()->getBruteVal());
        $checkedActions = (is_array($checkedActions)) ? $checkedActions : array();

         $checksAction = array();
         foreach($actions as $action) {
            $checksAction[] = \AckCore\HtmlElements\Check::getInstance(true)
                                                ->setChecked(in_array($action, $checkedActions))
                                                ->setTitle($action)
                                                ->setValue($action)
                                                ->setPermission($defaultPermission)
                                                ->setName("actions");
         }

          $blockActions = \AckCore\HtmlElements\CheckBlock::getInstance()->setChecks($checksAction)
          ->setTitle("Actions")
          ->setName("actions")
          ->setPermission($defaultPermission)
          ->render();
      ?>
</div>
