

    <div class="modulo <?= $controllerName ?>">
    	  <?php \AckCore\HtmlElements\Explain::getInstance()->setName("moduleDescription")->render();?>

        <div class="slide colunas">
        	<div class="collumA form">

               <?php
					\AckCore\HtmlElements\Input::Factory($row->vars["titulopt"])->render();
					\AckCore\HtmlElements\TextEditor::Factory($row->vars["conteudopt"])->render();
				?>


            </div><!-- END collumA -->
            <!-- • • • • -->
            <div class="collumB">
                 <?php echo $this->visible($row,$disableVisible) ?>
                <?php
\AckCore\HtmlElements\LanguageSelector::getInstance()->render() ?>
            </div>

            <span class="clearBoth"></span>
        </div><!-- END slide -->
    </div><!-- END modulo -->
